### ISSUE TITLE
Docker config

### ISSUE THREAD

**Issue by groupsky** [mh-community-tools/mh-hunt-helper#62]
I'm using a simple `docker-compose.yml` config to work the the backups so it may be useful to others if included in the repo.

```
db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=mhhunthelper
  volumes:
    - "./DB/hunthelper_nightly.sql.gz:/docker-entrypoint-initdb.d/backup01.sql.gz"
    - "./DB/converter_weekly.sql.gz:/docker-entrypoint-initdb.d/backup02.sql.gz"
adminer:
  image: adminer
  links:
    - db:db
  ports:
    - "8080:8080"
```

To use it, just need to execute `docker-compose up`
